name: "Coverage"

on:
    pull_request:
    push:
        branches: ["*"]
    schedule:
        - cron: "0 8 * * 1" # Spuštění každé pondělí v 8:00

jobs:
    coverage:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  extensions: mbstring
                  coverage: phpdbg
                  tools: composer

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Initialize environment
              run: make init

            - name: Run coverage
              run: make coverage
