name: PHPStan Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  phpstan:
    name: Run PHPStan
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1' # Specify your PHP version
          extensions: mbstring, intl, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=300
          coverage: none

      # Install dependencies using Composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # Run PHPStan
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --memory-limit=512M
