name: "Phpunit"

on:
    pull_request:

    push:
        branches: [ "*" ]

    schedule:
        - cron: "0 8 * * 1"

jobs:
    test82:
        name: "Phpunit with PHP 8.2"
        runs-on: ubuntu-latest
        steps:
            - name: Set up PHP 8.2
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.composer/cache
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

            - name: Install Composer dependencies
              run: composer install --no-interaction --prefer-dist

            - name: Run PHPUnit tests
              run: make init tests

    test81:
        name: "Phpunit with PHP 8.1"
        runs-on: ubuntu-latest
        steps:
            - name: Set up PHP 8.1
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'

            - name: Cache Composer dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.composer/cache
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

            - name: Install Composer dependencies
              run: composer install --no-interaction --prefer-dist

            - name: Run PHPUnit tests
              run: make init tests
